### ISSUE TITLE
[Error] no such file or directory

### ISSUE THREAD

**Issue by DragonVsKira** [anidl/funimation-downloader-nx#18]
** Main info: **

Script version: Funimation Downloader NX 4.6.0
Show ID: 
Episode ID: 

** Additional Info: **
=== Funimation Downloader NX 4.6.0 ===

Error: ENOENT: no such file or directory, access 'A:\1.Funimation-Rip\1\funimation-downloader-nx-4.5.1-win64\videos/'
    at Object.accessSync (fs.js:195:3)
    at Object.<anonymous> (J:\1.Funimation-Rip\1\funimation-downloader-nx-4.6.0-win64-Copy\funi.js:158:8)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -4058,
  syscall: 'access',
  code: 'ENOENT',
  path: 'A:\\1.Funimation-Rip\\1\\funimation-downloader-nx-4.5.1-win64\\videos/'
}
[ERROR] undefined

**Comment by anidl** [comment]
create videos folder in app folder
