### ISSUE TITLE
[BUG] Random UnhandledPromiseRejectionWarning when acquiring m3u8 url

### ISSUE THREAD

**Issue by shinji257** [anidl/funimation-downloader-nx#22]
** Main info: **

Script version: Latest git so... 4.6.0?
Show ID: 594522
Episode ID: 26

** Additional Info: **
The above information is an example but not really definitive.  It is intermittent and random when it will happen.  I can't seem to tell why it happens as trying again will almost cause it to actually work without issue.  It doesn't happen just because I'm running a bunch of requests as sometimes it hits on the first one.  However I did heed nodejs's request and added `--trace-warnings` so I can get something more detailed for you.

```
[INFO] Sword Art Online - S2E01 - The World of Guns
[INFO] Available streams (Non-Encrypted):
[#603604] Japanese [Uncut] (selected)
[#603613] English [Uncut]
(node:20285) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: 1867195_Japanese_21077844-c2e2-e811-8175-020165574d09_Layer1.m3u8
    at onParseError (internal/url.js:256:9)
    at new URL (internal/url.js:332:5)
    at downloadStreams (/home/shinji/funimation-downloader-nx/funi.js:493:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getEpisode (/home/shinji/funimation-downloader-nx/funi.js:446:13)
    at async getShow (/home/shinji/funimation-downloader-nx/funi.js:339:13)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:20285) TypeError [ERR_INVALID_URL]: Invalid URL: 1867195_Japanese_21077844-c2e2-e811-8175-020165574d09_Layer1.m3u8
    at onParseError (internal/url.js:256:9)
    at new URL (internal/url.js:332:5)
    at downloadStreams (/home/shinji/funimation-downloader-nx/funi.js:493:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getEpisode (/home/shinji/funimation-downloader-nx/funi.js:446:13)
    at async getShow (/home/shinji/funimation-downloader-nx/funi.js:339:13)
(node:20285) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by nijave** [comment]
So it looks like it's trying to use a filename as a URL in some cases? https://nodejs.org/api/errors.html#errors_err_invalid_url

`Invalid URL: 1867195_Japanese_21077844-c2e2-e811-8175-020165574d09_Layer1.m3u8` isn't a URL--it's just a file name. Maybe at times relative file names are being returned on there's a parsing error happening somewhere?

**Comment by nijave** [comment]
I think this is the same issue https://github.com/anidl/funimation-downloader-nx/issues/11

**Comment by anidl** [comment]
should be fixed with latest version
