### ISSUE TITLE
Script failing to start

### ISSUE THREAD

**Issue by Lawrence575** [anidl/funimation-downloader-nx#26]
![96eoA8a 1](https://user-images.githubusercontent.com/53096166/93692572-0ef0b480-fab2-11ea-9090-46deed802bc0.png)

** Main info: **
Error: Cannot find module 'got'
Require stack:
- X:\Downloads\funimation-downloader-nx-4.6.1-win64\funi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (X:\Downloads\funimation-downloader-nx-4.6.1-win64\funi.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'X:\\Downloads\\funimation-downloader-nx-4.6.1-win64\\funi.js' ]

Script version: latest
Show ID: n/a
Episode ID: n/a

** Additional Info: **

**Comment by anidl** [comment]
If you use js version, install modules first
