### ISSUE TITLE
[WARN] Detected specific align param, please contact developer

### ISSUE THREAD

**Issue by jmsether** [anidl/funimation-downloader-nx#42]
[WARN] Detected specific align param, please contact developer
(node:18752) UnhandledPromiseRejectionWarning: ReferenceError: cosnole is not defined
    at convertToAssLine (C:\Users\jmset\Desktop\funimation-downloader-nx-master\modules\module.vttconvert.js:76:9)
    at convertToAss (C:\Users\jmset\Desktop\funimation-downloader-nx-master\modules\module.vttconvert.js:61:13)
    at module.exports (C:\Users\jmset\Desktop\funimation-downloader-nx-master\modules\module.vttconvert.js:181:12)
    at downloadStreams (C:\Users\jmset\Desktop\funimation-downloader-nx-master\funi.js:549:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getEpisode (C:\Users\jmset\Desktop\funimation-downloader-nx-master\funi.js:368:13)
    at async getShow (C:\Users\jmset\Desktop\funimation-downloader-nx-master\funi.js:251:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AnAppleforlife** [comment]
Is this still an issue with the current version?

**Comment by izu-co** [comment]
I would assume that this issue has been resolved. If not, reopen it or create a new one, please.
