### ISSUE TITLE
[BUG] language not being applied

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [anidl/funimation-downloader-nx#63]
** Main info: **

Script version: 4.8.0-beta.1
Show ID: 1174171
Episode ID: 11

** Additional Info: **

the language tag is not being set by FFmpeg

since the issue mentioned here: https://github.com/anidl/funimation-downloader-nx/issues/54#issuecomment-831451148 in regards to mkvmerge not recognising the `--language 1` tag properly I switched to ffmpeg, however, the language tag is not even properly applied at all when muxiung.

![Screen Shot 2021-05-05 at 7 21 47 pm](https://user-images.githubusercontent.com/2242880/117121412-e4046800-add7-11eb-8d61-5e228a8be6ed.jpg)

this even happens with your build @AnAppleforlife 

I think for both ffmpeg & mkvmerge it needs to output as `language=en` for English & so forth for different languages

here is a list printed from the help page from mkvmerge of all the language tags
[1.txt](https://github.com/anidl/funimation-downloader-nx/files/6426161/1.txt)

**Comment by AnAppleforlife** [comment]
Working on it

**Comment by AnAppleforlife** [comment]
It should now be fine both with FFmpeg and mkvmerge (no promises made for mkvmerge tho).

**Comment by XxUnkn0wnxX** [comment]
ffmpeg has been fixed, mkvmerge process stated but never finished

```
> "mkvmerge" @"/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].json"
mkvmerge v56.1.0 ('My Friend') 64-bit
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].ts': Using the demultiplexer for the format 'MPEG transport stream'.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].en.ts': Using the demultiplexer for the format 'AAC'.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].en.ts' track 0: Using the output module for the format 'AAC'.
Warning: '/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].ts': A track with the ID 1 was requested but not found in the file. The corresponding option will be ignored.
The file '/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].mkv' has been opened for writing.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 7 seconds.
node:child_process:707
    err = new Error(msg);
          ^

Error: Command failed: "/usr/local/bin/mkvmerge" @"/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].json"
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at Object.exec (/Users/ADMIN/Apps/Animie/AnAppleforlife/funimation-downloader-nx/node_modules/sei-helper/src/main.js:174:30)
    at downloadStreams (/Users/ADMIN/Apps/Animie/AnAppleforlife/funimation-downloader-nx/funi.js:678:14)
    at async getEpisode (/Users/ADMIN/Apps/Animie/AnAppleforlife/funimation-downloader-nx/funi.js:381:13)
    at async getShow (/Users/ADMIN/Apps/Animie/AnAppleforlife/funimation-downloader-nx/funi.js:258:13) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 24954,
  stdout: null,
  stderr: null
}
```

**Comment by XxUnkn0wnxX** [comment]
when I pass the json file manually, no issues

```
 mkvmerge @"[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].json"
mkvmerge v56.1.0 ('My Friend') 64-bit
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].ts': Using the demultiplexer for the format 'MPEG transport stream'.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].en.ts': Using the demultiplexer for the format 'AAC'.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].en.ts' track 0: Using the output module for the format 'AAC'.
Warning: '/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].ts': A track with the ID 1 was requested but not found in the file. The corresponding option will be ignored.
The file '/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].mkv' has been opened for writing.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Sleepy Princess in the Demon Castle - 11 [1080p].ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 6 seconds.
```

so it's erroring out after mkvmerge finishes...

**Comment by AnAppleforlife** [comment]
It should be fixed now.

**Comment by XxUnkn0wnxX** [comment]
![Screen Shot 2021-05-06 at 1 31 50 am](https://user-images.githubusercontent.com/2242880/117167937-0fed1100-ae0b-11eb-9cc2-47385d5a3221.jpg)

I think you set the wrong track.. the video file got set instead of audio...
no errors or warnings this time though...

**Comment by AnAppleforlife** [comment]
Should be fixed. Sorry for the inconvenience.
