### ISSUE TITLE
[BUG] Getting an error

### ISSUE THREAD

**Issue by JunkMeal** [anidl/funimation-downloader-nx#69]
** Main info: **

Script version: 4.8.0 BETA
Show ID: 30696
Episode ID: 2

** Additional Info: **
Got an unhandled error (request error)
```shell
(node:26825) UnhandledPromiseRejectionWarning: RequestError: Hostname/IP does not match certificate's altnames: Host: d33et77evd9bgg.cloudfront.net. is not in the cert's altnames: DNS:abcsys.cz, DNS:www.abcsys.cz
    at ClientRequest.<anonymous> (/home/junkmeal/Documents/funimation-downloader-nx-4.8.0-beta.1/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/home/junkmeal/Documents/funimation-downloader-nx-4.8.0-beta.1/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Object.checkServerIdentity (tls.js:297:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507:27)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

(happenned at the end of downloading)

**Comment by AnAppleforlife** [comment]
It is working fine for me. If you retry does the error occur again?

**Comment by JunkMeal** [comment]
sorry for replying so late, i tried again and it seems to work
