### ISSUE TITLE
Not going through muxing.[BUG] 

### ISSUE THREAD

**Issue by Pain2790** [anidl/funimation-downloader-nx#88]
The download does not go throught the Muxing process to transfer to .mkv thus halting a multiple downloads. Please see below:

> "mkvmerge" @"videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - 01 [810p].json"
mkvmerge v59.0.0 ('Shining Star') 64-bit
Error: '' is not a valid IETF BCP 47/RFC 5646 language tag in '--language 1:'. Additional information from the parser: The value does not adhere to the general structure of IETF BCP 47/RFC 5646 language tags.
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: "C:\funimation-downloader-nx-master\bin\mkvmerge.EXE" @"videos\[Funimation] Mushoku Tensei_ Jobless Reincarnation - 01 [810p].json"
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exec (C:\funimation-downloader-nx-master\node_modules\sei-helper\src\main.js:174:30)
    at downloadStreams (C:\funimation-downloader-nx-master\funi.js:799:14)
    at async getEpisode (C:\funimation-downloader-nx-master\funi.js:375:13)
    at async getShow (C:\funimation-downloader-nx-master\funi.js:252:13) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 9620,
  stdout: null,
  stderr: null

Script version: 7.20.0
Show ID: Mushoku Tensei: Jobless Reincarnation
Episode ID:  1 - 11

** Additional Info: **

**Comment by Pain2790** [comment]
Sorry,
also would like to add that the episode does fully download before erroring out.

**Comment by izu-co** [comment]
This tool is unmaintained. Please see my fork  for a updated version.
